spring.application.name=stock-insight-api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT (???)
jwt.secret=CHANGE_ME_TO_LONG_RANDOM_STRING_CHANGE_ME_TO_LONG_RANDOM_STRING
jwt.expiration-seconds=3600
